export { About } from './About/About'
export { Book } from './Book/Book'
export { Home } from './Home/Home'
export { Login } from './Login/Login'
export { Profile } from './Profile/Profile'
export { Register } from './Register/Register'
export { NotFound } from './NotFound/Notfound'
